<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GraphicsCore/GraphicsCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model/" />
    <Folder Include="Buffer/" />
    <Folder Include="Textures/" />
  </ItemGroup>

</Project>
