<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UserSecretsId>838c1340-abc6-4e7d-84ce-ed0dc814b872</UserSecretsId>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../GraphicsCore/GraphicsCore.csproj" />
    <ProjectReference Include="../VulkanManager/VulkanManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MSDF-Sharp.Core" Version="1.0.2" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="SpaceWizards.SharpFont" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Slots/" />
  </ItemGroup>

</Project>
