<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CoreManager/CoreManager.csproj" />
    <ProjectReference Include="../GraphicsCore/GraphicsCore.csproj" />
    <ProjectReference Include="../PrimitiveCore/PrimitiveCore.csproj" />
    <ProjectReference Include="../TextCore/TextCore.csproj" />
    <ProjectReference Include="../VulkanManager/VulkanManager.csproj" />
    <ProjectReference Include="../Units/Units.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Assimp" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Input.Sdl" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Maths" Version="2.23.0" />
    <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="Silk.NET.Windowing.Sdl" Version="2.23.0" />
  </ItemGroup>

</Project>
